name: fitlife_mini
description: "A mobile fitness tracking application designed for offline-first experience."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  fl_chart: ^1.1.1
  awesome_notifications: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
